name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'
    
    - name: Build and Test Frontend
      run: |
        cd frontend
        npm install
        npm run lint
        npm run build

    - name: Build and Test Backend
      run: |
        cd backend
        npm install
        npx tsc --noEmit
        npm run test
        npm run build
